services:
  
  lostfound-matcher:
    build:
      context: ./
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./src:/lostfound-matcher/src
      - ./data:/lostfound-matcher/data
      - ./mongo_config:/lostfound-matcher/mongo_config

  mongodb:
    image: mongo:5.0.7
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=lostfound-matcher-db
    volumes:
      - ./data:/data/db
      - ./mongo_config:/data/configdb
    ports:
      - "27017:27017"
